config/routes.rb
Rails.application.routes.draw do
  resource :user
  resource :session
  resources :login, only: [:index]
  namespace :api, defaults: { format: :json } do
    resources :profiles
    resources :photos
    resources :comments
    resources :subscriptions
  end

  delete 'login' => 'login#destroy'

  root to: "static_pages#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :photo_id, :commenter_id, :body, presence: true

  belongs_to :author, foreign_key: :commenter_id, class: User
end

app/models/login.rb
class Login < ActiveRecord::Base
  validates :user_id, presence: true
  validates :session_token, uniqueness: true, presence: true

  belongs_to :user

  def self.find_all_logins_for_user(user)
    Login.where(user_id: user.id)
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  paginates_per 5

  default_scope { order('updated_at DESC') }

  validates :url, presence: true

  belongs_to :owner, foreign_key: :owner_id, class: User

  has_many :comments
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :owner_id, presence: true

  belongs_to :owner, foreign_key: :owner_id, class: User

  has_many :photos, through: :owner
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates :follower_id, :followee_id, presence: true

  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  belongs_to :followee, foreign_key: :followee_id, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 8, allow_nil: true }

  after_initialize do |user|
    user.session_token ||= create_session_token
  end

  has_many :logins
  has_one :profile
  has_many :photos, foreign_key: :owner_id

  has_many :follows, foreign_key: :followee_id, class_name: "Subscription"
  has_many :followers, through: :follows, source: :follower

  has_many :followees, foreign_key: :follower_id, class_name: "Subscription"
  has_many :favorite_people, through: :followees, source: :followee
  has_many :favorite_peoples_photos, through: :favorite_people, source: :photos

  def create_session_token
    SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password

    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user_instance = User.find_by(username: username)
    if user_instance.is_password?(password)
      return user_instance
    end

    nil
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController

  def index
    @comments = Comment.where( photo_id: comment_params[:photo_id])
    render :index
  end

  def create
    commenter_id = current_user.id
    total_comment_params = comment_params.merge({ commenter_id: commenter_id })
    @comment = Comment.create(total_comment_params)
    render :show
  end

  private

  def comment_params
    params.require(:comment).permit(:photo_id, :body)
  end
end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController
  def show
    @photo = Photo.find(params[:id])
    render json: @photo
  end

  def index
    page = params[:page] || 1
    @photos = current_user.favorite_peoples_photos.page(page)
    @page_number = page.to_i
    @total_pages = @photos.total_pages
    render :index
  end

  def create
    owner_id = current_user.id
    total_photo_params = photo_params.merge({ owner_id: owner_id })
    @photo = Photo.create!(total_photo_params)
    render json: @photo
  end

  private

  def photo_params
    params.require(:photo).permit(:url, :owner_id, :cloudinary_id)
  end
end

app/controllers/api/profiles_controller.rb
class Api::ProfilesController < ApplicationController
  def show
    user_id = params[:id]
    @profile = Profile.where(owner_id: user_id).first
    @photos = @profile.photos
    render :show
  end

  def index
    @profiles = Profile.all
    render :index
  end
end

app/controllers/api/subscriptions_controller.rb
class Api::SubscriptionsController < ApplicationController
  def create
    subscription = Subscription.create(
      follower_id: current_user.id,
      followee_id: params[:followee_id]
    )
    render json: subscription
  end

  def destroy
    subscription = Subscription.where(
      follower_id: current_user.id,
      followee_id: params[:followee_id]
    ).first
    subscription.destroy
  end

  private

  def subscription_params
    params.require(follow).permit(:followee_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    login_info = Login.find_by(session_token: session[:session_token])
    if login_info
      login_info.user
    else
      nil
    end
  end

  def create_session_token
    SecureRandom.urlsafe_base64
  end

  def login_user!(options = {})
    @user = User.find_by_credentials(params[:user][:username],
                                     params[:user][:password])
    if @user
      new_token = create_session_token
      session[:session_token] = new_token
      userid = @user.id
      user_info = {user_id: userid, session_token: new_token}
      Login.create(user_info)

      if !(options.empty?) && options[:show]
        redirect_to "/#profiles/#{options[:profile_id]}"
      else
        redirect_to "/"
      end
    else
      render :new
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @logins = Login.find_all_logins_for_user(current_user)

    render :index
  end

  def destroy
    @logins = Login.find_all_logins_for_user(current_user)
    id = params[:login][:unique_id]
    user_id = current_user.id

    Login.where(user_id: user_id, id: id).destroy_all

    redirect_to new_session
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_logged_in, only: [:new, :create]

  def already_logged_in
    if current_user
      render json: "You have already logged in"
    end
  end

  def new
    @user = User.new

    render :new
  end

  def create
    login_user!
  end

  def destroy
    @user = current_user
    userid = @user.id
    Login.where(user_id: userid, session_token: session[:session_token]).destroy_all
    session[:session_token] = nil
    redirect_to "/"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    redirect_to new_session_url unless current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_logged_in, only: [:new, :create]

  def already_logged_in
    if current_user
      redirect_to "/"
    end
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      profile = Profile.new({ owner_id: @user.id })
      profile.save!
      login_user!({ show: true, profile_id: profile.id })
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pictolater</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<head>
  <script> var currentUser = "<%= current_user.try(:username) %>" </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>
  <script> $.cloudinary.config({ cloud_name: "dcd7no2gu", api_key: 362112799383995 }) </script>

</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">PictoLater</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="navbar-form navbar-left">
          <div class="cloudinary-holder">
            <button class="photopick btn btn-default"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span></button>
          </div>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><a href="#profiles/<%= current_user.id %>"><%= current_user.username %></a></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Sign Out", session_url, method: :delete, class: "add-button" %>
            </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="main">
  </div>

  <script> $(Pictolater.initialize); </script>
</body>

app/views/users/new.html.erb
<h3>Create a new user</h3>
<form action="/user" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  
  <label for="username">Username:</label>
  <input type="text" name="user[username]" value="<%= @user.username %>" id="username">

  <label for="email">Email:</label>
  <input type="text" name="user[email]" value="<%= @user.email %>" id="email">

  <label for="password">Password:</label>
  <input type="password" name="user[password]" id="password">

  <input type="submit" value="Sign Up">
</form>